### ISSUE TITLE
Address incompability with assertj-core 3.12+

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-neo4j#17]
With assertj-core 3.12.0 it is not longer possible to create `IterableAssert` from an `Iterator` which makes creating `ResultAssert` instances to fail.

A possible fix is to convert `Result` to an `Iterable` in `ResultAssert` constructor.

**Comment by fbiville** [comment]
Fixed by @bel3atar in tonight's Hackergarten \m/

**Comment by joel-costigliola** [comment]
Awesome guys!
